-- M7: quotas, the usage meter, and the columns retention sweeps on.
--
-- Generated by drizzle-kit, with the RLS block at the bottom added by hand —
-- the same split `0001_rls.sql` made, but in one migration rather than two on
-- purpose: a tenant table that exists for even one migration without its
-- policy is a tenant table that can be read across orgs, and `TENANT_TABLES`
-- in `schema.ts` (which the isolation test reads) would have started failing
-- the moment `usage_events` was added there.
--
-- Everything else here is additive and nullable, so it applies to a populated
-- database without a backfill: an existing video simply has no recorded size
-- until the retention sweep reconciles it against storage, and an existing org
-- has no limit overrides, which means the platform defaults in `env.ts`.

CREATE TABLE "usage_events" (
	"id" text PRIMARY KEY NOT NULL,
	"org_id" text NOT NULL,
	"kind" text NOT NULL,
	"quantity" double precision NOT NULL,
	"video_id" text,
	"export_id" text,
	"detail" text,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "exports" ADD COLUMN "size_bytes" bigint;--> statement-breakpoint
ALTER TABLE "org_settings" ADD COLUMN "transcription_minutes_limit" integer;--> statement-breakpoint
ALTER TABLE "org_settings" ADD COLUMN "storage_bytes_limit" bigint;--> statement-breakpoint
ALTER TABLE "org_settings" ADD COLUMN "retention_days" integer;--> statement-breakpoint
ALTER TABLE "org_settings" ADD COLUMN "suspended_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "org_settings" ADD COLUMN "suspended_reason" text;--> statement-breakpoint
ALTER TABLE "videos" ADD COLUMN "size_bytes" bigint;--> statement-breakpoint
ALTER TABLE "usage_events" ADD CONSTRAINT "usage_events_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_usage_events_org_kind_occurred" ON "usage_events" USING btree ("org_id","kind","occurred_at");--> statement-breakpoint

-- The ledger is tenant data like any other: the same policy, the same FORCE,
-- and the same fail-closed comparison against `app.current_org_id`. See
-- `0001_rls.sql`'s header for why the `missing_ok` form of `current_setting`
-- is the one used.
--
-- Worth naming, because it is the one table where an *escaped* read would be
-- worse than a leaked row: `usage_events` is how much a tenant has spent, and
-- the worker writes it from a process that runs every org's jobs in turn.
CREATE POLICY org_isolation ON usage_events
  USING (org_id = current_setting('app.current_org_id', true))
  WITH CHECK (org_id = current_setting('app.current_org_id', true));
--> statement-breakpoint
ALTER TABLE usage_events ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE usage_events FORCE ROW LEVEL SECURITY;
